version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gerenciamento_tarefas
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Serviço Prisma (usando a imagem do Node.js)
  prisma:
    image: node:16
    container_name: prisma
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "postgresql://postgres:admin@postgres:5432/gerenciamento_tarefas"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"  # Adicionando essa linha
    command: ["npx", "prisma", "generate"]
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
